spring.application.name=gestordocumento
# Puerto del servidor
server.port=8080

# Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gestor_documental_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=20000

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Tamaño máximo de subida de archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Directorio donde se guardarán físicamente los archivos
storage.location=uploads

# Configuración del servidor de Kafka (por defecto en local es localhost:9092)
spring.kafka.bootstrap-servers=localhost:9092

# Serializadores necesarios para que Spring pueda crear el bean KafkaTemplate automáticamente
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer